"""
Genome Corporation — PDF Generation Microservice
Deploy on Railway: railway up
Endpoint: POST /generate  -> returns PDF binary
"""

from flask import Flask, request, send_file, jsonify
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable, Flowable
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas
import io, os, base64, requests
from datetime import datetime

app = Flask(__name__)

# ── Brand Colors ──────────────────────────────────────────────
GOLD        = HexColor('#D4A017')
DARK_GREEN  = HexColor('#2D5016')
MID_GREEN   = HexColor('#4A7C2F')
LIGHT_GOLD  = HexColor('#F5E6B3')
LIGHT_GREEN = HexColor('#EAF2E3')
DARK_TEXT   = HexColor('#1A1A1A')
MID_GREY    = HexColor('#666666')
WHITE       = colors.white
RED_ALERT   = HexColor('#C0392B')
AMBER       = HexColor('#E67E22')
GREEN_OK    = HexColor('#27AE60')
PAGE_W, PAGE_H = A4

STATUS_COLORS = {
    'Blocked':   RED_ALERT,
    'On Track':  AMBER,
    'Completed': GREEN_OK,
}

LOGO_PATH = os.path.join(os.path.dirname(__file__), 'genome_icon_only.png')


# ── Progress Bar Flowable ─────────────────────────────────────
class ProgressBar(Flowable):
    def __init__(self, pct, width, height=11, color=AMBER):
        Flowable.__init__(self)
        self.pct = pct
        self.width = width
        self.height = height
        self.color = color

    def draw(self):
        self.canv.setFillColor(HexColor('#E0E0E0'))
        self.canv.roundRect(0, 0, self.width, self.height, 4, fill=1, stroke=0)
        fill_w = max(8, self.width * self.pct / 100)
        self.canv.setFillColor(self.color)
        self.canv.roundRect(0, 0, fill_w, self.height, 4, fill=1, stroke=0)
        if fill_w > 20:
            self.canv.setFillColor(WHITE)
            self.canv.setFont('Helvetica-Bold', 7)
            self.canv.drawCentredString(fill_w / 2, 2, f'{self.pct}%')


# ── Header/Footer Canvas ──────────────────────────────────────
def make_canvas_class(d):
    class HFC(canvas.Canvas):
        def __init__(self, *args, **kwargs):
            canvas.Canvas.__init__(self, *args, **kwargs)
            self._saved = []

        def showPage(self):
            self._saved.append(dict(self.__dict__))
            self._startPage()

        def save(self):
            n = len(self._saved)
            for state in self._saved:
                self.__dict__.update(state)
                self._draw(n)
                canvas.Canvas.showPage(self)
            canvas.Canvas.save(self)

        def _draw(self, total):
            w, h = A4
            # Header
            self.setFillColor(DARK_GREEN)
            self.rect(0, h - 28*mm, w, 28*mm, fill=1, stroke=0)
            if os.path.exists(LOGO_PATH):
                self.drawImage(LOGO_PATH, 8*mm, h - 26*mm, width=38*mm,
                               height=23*mm, preserveAspectRatio=True, mask='auto')
            self.setFillColor(WHITE)
            self.setFont('Helvetica-Bold', 13)
            self.drawString(52*mm, h - 12*mm, 'Genome Corporation')
            self.setFont('Helvetica', 8)
            self.setFillColor(LIGHT_GOLD)
            self.drawString(52*mm, h - 18*mm, 'Site Progress Report  |  Confidential')
            self.setFillColor(WHITE)
            self.setFont('Helvetica', 8)
            self.drawRightString(w - 10*mm, h - 12*mm, d.get('report_date', ''))
            self.drawRightString(w - 10*mm, h - 18*mm, f"Site: {d.get('site_id','N/A')}")
            self.setStrokeColor(GOLD)
            self.setLineWidth(2)
            self.line(0, h - 28*mm, w, h - 28*mm)
            # Footer
            self.setFillColor(DARK_GREEN)
            self.rect(0, 0, w, 14*mm, fill=1, stroke=0)
            self.setFillColor(GOLD)
            self.setFont('Helvetica-Bold', 7)
            self.drawString(10*mm, 8*mm, 'GENOME CORPORATION')
            self.setFillColor(WHITE)
            self.setFont('Helvetica', 7)
            self.drawString(10*mm, 4*mm,
                'This report is auto-generated by Genome AI Operations System.')
            self.setFillColor(GOLD)
            self.setFont('Helvetica-Bold', 8)
            self.drawRightString(w - 10*mm, 6*mm, f'Page {self._pageNumber} of {total}')
            self.setStrokeColor(GOLD)
            self.setLineWidth(1.5)
            self.line(0, 14*mm, w, 14*mm)
    return HFC


# ── PDF Builder ───────────────────────────────────────────────
def build_pdf(d):
    buf = io.BytesIO()
    status_color = STATUS_COLORS.get(d.get('status', 'On Track'), AMBER)

    doc = SimpleDocTemplate(buf, pagesize=A4,
        topMargin=34*mm, bottomMargin=20*mm,
        leftMargin=14*mm, rightMargin=14*mm)

    def S(name, **kw):
        return ParagraphStyle(name, **kw)

    s_section = S('ST', fontName='Helvetica-Bold', fontSize=9,
                  textColor=WHITE, spaceAfter=0, leading=12)
    s_label   = S('LB', fontName='Helvetica-Bold', fontSize=8.5,
                  textColor=MID_GREY, spaceAfter=2, leading=11)
    s_value   = S('VL', fontName='Helvetica', fontSize=9.5,
                  textColor=DARK_TEXT, spaceAfter=4, leading=13)
    s_body    = S('BD', fontName='Helvetica', fontSize=9,
                  textColor=DARK_TEXT, spaceAfter=4, leading=14)
    s_note    = S('NT', fontName='Helvetica-Oblique', fontSize=8,
                  textColor=MID_GREY, spaceAfter=2, leading=11)

    def sec_hdr(title):
        t = Table([[Paragraph(f'  {title}', s_section)]],
                  colWidths=[PAGE_W - 28*mm])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), DARK_GREEN),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
        ]))
        return t

    def badge(status):
        t = Table([[Paragraph(f'  \u25cf {status.upper()}  ',
                              S('BG', fontName='Helvetica-Bold', fontSize=10,
                                textColor=WHITE, leading=14))]],
                  colWidths=[44*mm])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), status_color),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
        ]))
        return t

    story = []
    story.append(Spacer(1, 4*mm))

    # Overview
    ov = Table([
        [Paragraph('<b>CLIENT</b>', s_label), Paragraph('<b>SITE ID</b>', s_label),
         Paragraph('<b>PHASE</b>', s_label),  Paragraph('<b>SUPERVISOR</b>', s_label)],
        [Paragraph(d.get('client_name','N/A'), s_value),
         Paragraph(d.get('site_id','N/A'), s_value),
         Paragraph(d.get('work_phase','N/A'), s_value),
         Paragraph(d.get('supervisor_name','N/A'), s_value)],
    ], colWidths=[50*mm, 35*mm, 65*mm, 33*mm])
    ov.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), LIGHT_GREEN),
        ('BOX', (0,0), (-1,-1), 0.5, HexColor('#CCCCCC')),
        ('INNERGRID', (0,0), (-1,-1), 0.3, HexColor('#DDDDDD')),
        ('TOPPADDING', (0,0), (-1,-1), 6), ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ('LEFTPADDING', (0,0), (-1,-1), 8), ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story += [ov, Spacer(1,5*mm)]

    # Status + Progress
    story.append(sec_hdr('CURRENT STATUS & PROGRESS'))
    story.append(Spacer(1, 3*mm))
    pct = int(d.get('progress_pct', 0))
    left = Table([
        [Paragraph('STATUS', s_label)],
        [badge(d.get('status','On Track'))],
        [Spacer(1,3*mm)],
        [Paragraph('OVERALL PROGRESS', s_label)],
        [ProgressBar(pct, 80*mm, 12, status_color)],
        [Paragraph(f'{pct}% Complete',
                   S('PC', fontName='Helvetica-Bold', fontSize=11,
                     textColor=status_color, leading=16))],
    ], colWidths=[90*mm])
    right = Table([
        [Paragraph('REPORT DATE', s_label)],
        [Paragraph(d.get('report_date',''), s_value)],
        [Spacer(1,2*mm)],
        [Paragraph('SUPERVISOR', s_label)],
        [Paragraph(d.get('supervisor_name','N/A'), s_value)],
        [Spacer(1,2*mm)],
        [Paragraph('SOURCE', s_label)],
        [Paragraph('Field Update — Genome AI', s_value)],
    ], colWidths=[80*mm])
    st = Table([[left, right]], colWidths=[95*mm, 88*mm])
    st.setStyle(TableStyle([
        ('VALIGN',(0,0),(-1,-1),'TOP'),
        ('LEFTPADDING',(0,0),(-1,-1),0),
        ('RIGHTPADDING',(0,0),(-1,-1),0),
    ]))
    story += [st, Spacer(1,5*mm)]

    # Work Done
    story.append(sec_hdr('WORK COMPLETED TODAY'))
    story.append(Spacer(1,3*mm))
    story.append(Paragraph(d.get('raw_text','N/A'), s_body))
    story.append(Spacer(1,5*mm))

    # Blockers
    story.append(sec_hdr('BLOCKERS & ISSUES'))
    story.append(Spacer(1,3*mm))
    bl = d.get('blockers','').strip()
    if bl and bl.lower() not in ('none','none reported',''):
        bt = Table([[Paragraph('\u26a0', S('W', fontName='Helvetica-Bold',
                                           fontSize=14, textColor=AMBER, leading=16)),
                     Paragraph(bl, s_body)]],
                   colWidths=[10*mm, PAGE_W-38*mm])
        bt.setStyle(TableStyle([
            ('BACKGROUND',(0,0),(-1,-1),HexColor('#FFF8E1')),
            ('BOX',(0,0),(-1,-1),0.5,AMBER),
            ('VALIGN',(0,0),(-1,-1),'MIDDLE'),
            ('TOPPADDING',(0,0),(-1,-1),7),
            ('BOTTOMPADDING',(0,0),(-1,-1),7),
            ('LEFTPADDING',(0,0),(-1,-1),6),
        ]))
        story.append(bt)
    else:
        ot = Table([[Paragraph('\u2713', S('OK', fontName='Helvetica-Bold',
                                            fontSize=12, textColor=GREEN_OK, leading=16)),
                     Paragraph('No blockers reported.', s_body)]],
                   colWidths=[10*mm, PAGE_W-38*mm])
        ot.setStyle(TableStyle([
            ('BACKGROUND',(0,0),(-1,-1),HexColor('#EAF7EF')),
            ('BOX',(0,0),(-1,-1),0.5,GREEN_OK),
            ('VALIGN',(0,0),(-1,-1),'MIDDLE'),
            ('TOPPADDING',(0,0),(-1,-1),7),
            ('BOTTOMPADDING',(0,0),(-1,-1),7),
            ('LEFTPADDING',(0,0),(-1,-1),6),
        ]))
        story.append(ot)
    story.append(Spacer(1,5*mm))

    # Next Actions
    story.append(sec_hdr('NEXT ACTIONS REQUIRED'))
    story.append(Spacer(1,3*mm))
    nt = Table([[Paragraph('\u2192', S('AR', fontName='Helvetica-Bold',
                                        fontSize=13, textColor=DARK_GREEN, leading=16)),
                 Paragraph(d.get('next_steps','N/A'), s_body)]],
               colWidths=[10*mm, PAGE_W-38*mm])
    nt.setStyle(TableStyle([
        ('BACKGROUND',(0,0),(-1,-1),LIGHT_GREEN),
        ('BOX',(0,0),(-1,-1),0.5,MID_GREEN),
        ('VALIGN',(0,0),(-1,-1),'MIDDLE'),
        ('TOPPADDING',(0,0),(-1,-1),7),
        ('BOTTOMPADDING',(0,0),(-1,-1),7),
        ('LEFTPADDING',(0,0),(-1,-1),6),
    ]))
    story += [nt, Spacer(1,6*mm)]

    # Signature row
    story.append(HRFlowable(width='100%', thickness=0.5, color=HexColor('#CCCCCC')))
    story.append(Spacer(1,4*mm))
    sig = Table([
        [Paragraph('Prepared by', s_label),
         Paragraph('Verified by', s_label),
         Paragraph('Report Reference', s_label)],
        [Paragraph('Genome AI Operations', s_note),
         Paragraph('Project Manager', s_note),
         Paragraph(f"{d.get('site_id','')}-{d.get('report_date','').replace(' ','-')}", s_note)],
        [Paragraph('_____________________', s_note),
         Paragraph('_____________________', s_note),
         Paragraph('', s_note)],
    ], colWidths=[60*mm, 70*mm, 53*mm])
    sig.setStyle(TableStyle([
        ('TOPPADDING',(0,0),(-1,-1),3),
        ('BOTTOMPADDING',(0,0),(-1,-1),3),
        ('LEFTPADDING',(0,0),(-1,-1),0),
        ('VALIGN',(0,0),(-1,-1),'TOP'),
    ]))
    story.append(sig)

    doc.build(story, canvasmaker=make_canvas_class(d))
    buf.seek(0)
    return buf


# ── Routes ────────────────────────────────────────────────────
@app.route('/generate', methods=['POST'])
def generate():
    try:
        d = request.get_json(force=True)
        buf = build_pdf(d)
        filename = f"Genome-{d.get('site_id','report')}-{d.get('report_date','').replace(' ','-')}.pdf"
        return send_file(buf, mimetype='application/pdf',
                         as_attachment=True,
                         download_name=filename)
    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/health', methods=['GET'])
def health():
    return jsonify({'status': 'ok', 'service': 'Genome PDF Service'})

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port)
